export const QuizActionTypes = {
    SET_QUIZ_QUESTIONS: "SET_QUIZ_QUESTIONS",
    INCREMENT_CORRECT_ANSWERS: "INCREMENT_CORRECT_ANSWERS",
    UPDATE_CURRENT_QUESTION: "UPDATE_CURRENT_QUESTION",
    RESET_GAME: "RESET_GAME",
  };
  